### ISSUE TITLE
Don't use dev-master

### ISSUE THREAD

**Issue by harikt** [Ray-Di/Ray.WebContextParam#1]
Hey @koriym , 

Don't use dev-master. Also I wonder whether you really was looking for 1.0 version or 2.0 version of aura/web .

Thanks!

**Comment by koriym** [comment]
Hi @harikt  Thanks for the reporting !

I will delete it (whole line is unnecessary now) Maybe I typed `composer require aura/web` at "minimum-stability": "dev".

**Comment by harikt** [comment]
:) .

**Comment by koriym** [comment]
@harikt Beside this error, How do you see this library ? 
Testing seems easier ? Too much Magic ?

**Comment by harikt** [comment]
@koriym personal taste. Don't like too much of the doc blocks.

**Comment by koriym** [comment]
@harikt I see. 
I made it by **inject-over-pull** design.
